version: "3.9"

services:
  graphql-engine:
    image: onfinality/subql-query:latest
    depends_on:
      - postgres
    environment:
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${POSTGRES_PASSWORD:-postgress}
      DB_DATABASE: ${DB_DATABASE:-postgres}
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
    command:
      - --name=turing
      - --playground
      - --indexer=http://subquery-node:3000
      - --unsafe
    restart: always
    networks:
      - oak-subql

  caddy:
    image: caddy
    environment:
      SITE_ADDRESS: ${SITE_ADDRESS:-localhost}
    ports:
      - ${CADDY_PORT_HTTP:-8880}:80
      - ${CADDY_PORT_HTTPS:-8443}:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${CADDY_DATA_PATH:-./data/caddy}:/data
    restart: always
    networks:
      - oak-subql

networks:
  oak-subql:
