specVersion: 0.2.0
name: neumann-subql
version: 0.0.4
description: Any queries for subquery for OAK's neumann network
repository: https://github.com/subquery/neumann-subql
schema:
  file: ./schema.graphql
network:
  endpoint: wss://neumann.api.onfinality.io/public-ws
  genesisHash: '0x8a671b9d609a2f753cb7618f5443e301e6300e07ea85c43956d81302d88fcd81'
  chaintypes:
    file: ./dist/chaintypes.js
  dictionary: https://api.subquery.network/sq/subquery/neumann-dictionary
dataSources:
  - kind: substrate/Runtime
    startBlock: 7000
    mapping:
      file: ./dist/index.js
      handlers:
        # - handler: handleBlock
        #   kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: automationTime
