specVersion: 0.2.0
name: neumann-subql
version: 0.0.4
description: Any queries for subquery for OAK's neumann network
repository: https://github.com/subquery/neumann-subql
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://neumann.api.onfinality.io/public-ws'
  genesisHash: '0x68577f68a47847fb974c220189333c46e83a899b6e375abf50b9a615d9019c20'
  chaintypes:
    file: ./dist/chaintypes.js
  dictionary: https://api.subquery.network/sq/subquery/neumann-dictionary
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers: 
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler