specVersion: 0.2.0
name: turing-subql
version: 0.0.4
description: Any queries for subquery for OAK's Turing network
repository: https://github.com/subquery/oak-subql
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://rpc.turing.oak.tech'
  genesisHash: '0x42e75532d6809775cef4b9ca8e4bb49be2dc1e87c9ff1ba299e78481b5cb3047'
  chaintypes:
    file: ./dist/chaintypes.js
  dictionary: https://api.subquery.network/sq/OAK-Foundation/turing-network
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers: 
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler