name: Prod Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  prod-deploy:
    name: Prod Deploy
    uses: ./.github/workflows/deploy.yml
    with:
      target_env: "prod"
    secrets:
      SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      SECRET_FILE: ${{ secrets.SECRET_FILE }}
      HOST: ${{ secrets.HOST }}
